/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiCompanionRouteImport } from './routes/api/companion'
import { Route as AppYouRouteImport } from './routes/_app.you'
import { Route as AppWindDownRouteImport } from './routes/_app.wind-down'
import { Route as AppUrgeShieldRouteImport } from './routes/_app.urge-shield'
import { Route as AppSosRouteImport } from './routes/_app.sos'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReflectRouteImport } from './routes/_app.reflect'
import { Route as AppPrivacyRouteImport } from './routes/_app.privacy'
import { Route as AppMemoriesRouteImport } from './routes/_app.memories'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppInsightsRouteImport } from './routes/_app.insights'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppHealRouteImport } from './routes/_app.heal'
import { Route as AppCompanionRouteImport } from './routes/_app.companion'
import { Route as AppCheckinRouteImport } from './routes/_app.checkin'
import { Route as AppPatternTagRouteImport } from './routes/_app.pattern.$tag'
import { Route as AppLetterIdRouteImport } from './routes/_app.letter.$id'
import { Route as AppHealSlugRouteImport } from './routes/_app.heal.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCompanionRoute = ApiCompanionRouteImport.update({
  id: '/api/companion',
  path: '/api/companion',
  getParentRoute: () => rootRouteImport,
} as any)
const AppYouRoute = AppYouRouteImport.update({
  id: '/you',
  path: '/you',
  getParentRoute: () => AppRoute,
} as any)
const AppWindDownRoute = AppWindDownRouteImport.update({
  id: '/wind-down',
  path: '/wind-down',
  getParentRoute: () => AppRoute,
} as any)
const AppUrgeShieldRoute = AppUrgeShieldRouteImport.update({
  id: '/urge-shield',
  path: '/urge-shield',
  getParentRoute: () => AppRoute,
} as any)
const AppSosRoute = AppSosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReflectRoute = AppReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoriesRoute = AppMemoriesRouteImport.update({
  id: '/memories',
  path: '/memories',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppInsightsRoute = AppInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppHealRoute = AppHealRouteImport.update({
  id: '/heal',
  path: '/heal',
  getParentRoute: () => AppRoute,
} as any)
const AppCompanionRoute = AppCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckinRoute = AppCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AppRoute,
} as any)
const AppPatternTagRoute = AppPatternTagRouteImport.update({
  id: '/pattern/$tag',
  path: '/pattern/$tag',
  getParentRoute: () => AppRoute,
} as any)
const AppLetterIdRoute = AppLetterIdRouteImport.update({
  id: '/letter/$id',
  path: '/letter/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppHealSlugRoute = AppHealSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => AppHealRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkin': typeof AppCheckinRoute
  '/companion': typeof AppCompanionRoute
  '/heal': typeof AppHealRouteWithChildren
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/journal': typeof AppJournalRoute
  '/memories': typeof AppMemoriesRoute
  '/privacy': typeof AppPrivacyRoute
  '/reflect': typeof AppReflectRoute
  '/settings': typeof AppSettingsRoute
  '/sos': typeof AppSosRoute
  '/urge-shield': typeof AppUrgeShieldRoute
  '/wind-down': typeof AppWindDownRoute
  '/you': typeof AppYouRoute
  '/api/companion': typeof ApiCompanionRoute
  '/heal/$slug': typeof AppHealSlugRoute
  '/letter/$id': typeof AppLetterIdRoute
  '/pattern/$tag': typeof AppPatternTagRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/checkin': typeof AppCheckinRoute
  '/companion': typeof AppCompanionRoute
  '/heal': typeof AppHealRouteWithChildren
  '/home': typeof AppHomeRoute
  '/insights': typeof AppInsightsRoute
  '/journal': typeof AppJournalRoute
  '/memories': typeof AppMemoriesRoute
  '/privacy': typeof AppPrivacyRoute
  '/reflect': typeof AppReflectRoute
  '/settings': typeof AppSettingsRoute
  '/sos': typeof AppSosRoute
  '/urge-shield': typeof AppUrgeShieldRoute
  '/wind-down': typeof AppWindDownRoute
  '/you': typeof AppYouRoute
  '/api/companion': typeof ApiCompanionRoute
  '/heal/$slug': typeof AppHealSlugRoute
  '/letter/$id': typeof AppLetterIdRoute
  '/pattern/$tag': typeof AppPatternTagRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/checkin': typeof AppCheckinRoute
  '/_app/companion': typeof AppCompanionRoute
  '/_app/heal': typeof AppHealRouteWithChildren
  '/_app/home': typeof AppHomeRoute
  '/_app/insights': typeof AppInsightsRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/memories': typeof AppMemoriesRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/reflect': typeof AppReflectRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/sos': typeof AppSosRoute
  '/_app/urge-shield': typeof AppUrgeShieldRoute
  '/_app/wind-down': typeof AppWindDownRoute
  '/_app/you': typeof AppYouRoute
  '/api/companion': typeof ApiCompanionRoute
  '/_app/heal/$slug': typeof AppHealSlugRoute
  '/_app/letter/$id': typeof AppLetterIdRoute
  '/_app/pattern/$tag': typeof AppPatternTagRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/checkin'
    | '/companion'
    | '/heal'
    | '/home'
    | '/insights'
    | '/journal'
    | '/memories'
    | '/privacy'
    | '/reflect'
    | '/settings'
    | '/sos'
    | '/urge-shield'
    | '/wind-down'
    | '/you'
    | '/api/companion'
    | '/heal/$slug'
    | '/letter/$id'
    | '/pattern/$tag'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/checkin'
    | '/companion'
    | '/heal'
    | '/home'
    | '/insights'
    | '/journal'
    | '/memories'
    | '/privacy'
    | '/reflect'
    | '/settings'
    | '/sos'
    | '/urge-shield'
    | '/wind-down'
    | '/you'
    | '/api/companion'
    | '/heal/$slug'
    | '/letter/$id'
    | '/pattern/$tag'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_app/checkin'
    | '/_app/companion'
    | '/_app/heal'
    | '/_app/home'
    | '/_app/insights'
    | '/_app/journal'
    | '/_app/memories'
    | '/_app/privacy'
    | '/_app/reflect'
    | '/_app/settings'
    | '/_app/sos'
    | '/_app/urge-shield'
    | '/_app/wind-down'
    | '/_app/you'
    | '/api/companion'
    | '/_app/heal/$slug'
    | '/_app/letter/$id'
    | '/_app/pattern/$tag'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiCompanionRoute: typeof ApiCompanionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/companion': {
      id: '/api/companion'
      path: '/api/companion'
      fullPath: '/api/companion'
      preLoaderRoute: typeof ApiCompanionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/you': {
      id: '/_app/you'
      path: '/you'
      fullPath: '/you'
      preLoaderRoute: typeof AppYouRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wind-down': {
      id: '/_app/wind-down'
      path: '/wind-down'
      fullPath: '/wind-down'
      preLoaderRoute: typeof AppWindDownRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/urge-shield': {
      id: '/_app/urge-shield'
      path: '/urge-shield'
      fullPath: '/urge-shield'
      preLoaderRoute: typeof AppUrgeShieldRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/sos': {
      id: '/_app/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof AppSosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reflect': {
      id: '/_app/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof AppReflectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memories': {
      id: '/_app/memories'
      path: '/memories'
      fullPath: '/memories'
      preLoaderRoute: typeof AppMemoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/insights': {
      id: '/_app/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof AppInsightsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heal': {
      id: '/_app/heal'
      path: '/heal'
      fullPath: '/heal'
      preLoaderRoute: typeof AppHealRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companion': {
      id: '/_app/companion'
      path: '/companion'
      fullPath: '/companion'
      preLoaderRoute: typeof AppCompanionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkin': {
      id: '/_app/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AppCheckinRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pattern/$tag': {
      id: '/_app/pattern/$tag'
      path: '/pattern/$tag'
      fullPath: '/pattern/$tag'
      preLoaderRoute: typeof AppPatternTagRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/letter/$id': {
      id: '/_app/letter/$id'
      path: '/letter/$id'
      fullPath: '/letter/$id'
      preLoaderRoute: typeof AppLetterIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/heal/$slug': {
      id: '/_app/heal/$slug'
      path: '/$slug'
      fullPath: '/heal/$slug'
      preLoaderRoute: typeof AppHealSlugRouteImport
      parentRoute: typeof AppHealRoute
    }
  }
}

interface AppHealRouteChildren {
  AppHealSlugRoute: typeof AppHealSlugRoute
}

const AppHealRouteChildren: AppHealRouteChildren = {
  AppHealSlugRoute: AppHealSlugRoute,
}

const AppHealRouteWithChildren =
  AppHealRoute._addFileChildren(AppHealRouteChildren)

interface AppRouteChildren {
  AppCheckinRoute: typeof AppCheckinRoute
  AppCompanionRoute: typeof AppCompanionRoute
  AppHealRoute: typeof AppHealRouteWithChildren
  AppHomeRoute: typeof AppHomeRoute
  AppInsightsRoute: typeof AppInsightsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppMemoriesRoute: typeof AppMemoriesRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppReflectRoute: typeof AppReflectRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppSosRoute: typeof AppSosRoute
  AppUrgeShieldRoute: typeof AppUrgeShieldRoute
  AppWindDownRoute: typeof AppWindDownRoute
  AppYouRoute: typeof AppYouRoute
  AppLetterIdRoute: typeof AppLetterIdRoute
  AppPatternTagRoute: typeof AppPatternTagRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCheckinRoute: AppCheckinRoute,
  AppCompanionRoute: AppCompanionRoute,
  AppHealRoute: AppHealRouteWithChildren,
  AppHomeRoute: AppHomeRoute,
  AppInsightsRoute: AppInsightsRoute,
  AppJournalRoute: AppJournalRoute,
  AppMemoriesRoute: AppMemoriesRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppReflectRoute: AppReflectRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppSosRoute: AppSosRoute,
  AppUrgeShieldRoute: AppUrgeShieldRoute,
  AppWindDownRoute: AppWindDownRoute,
  AppYouRoute: AppYouRoute,
  AppLetterIdRoute: AppLetterIdRoute,
  AppPatternTagRoute: AppPatternTagRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiCompanionRoute: ApiCompanionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
